[package]
name = "stable-diffusion-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stable-diffusion-trainer = { path = "../lib" }
clap = { version = "4", features = ["derive"] }
rfd = "0.13"