[package]
name = "stable-diffusion"
version.workspace = true
description.workspace = true
license.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
authors.workspace = true
keywords.workspace = true

[dependencies]
